package eu.kanade.tachiyomi.extension.vi.phemanga

import eu.kanade.tachiyomi.multisrc.mymangacms.MyMangaCMS

class PheManga : MyMangaCMS("Phê Manga", "https://phemanga.net", "vi") {
    override fun dateUpdatedParser(date: String): Long =
        runCatching { super.dateUpdatedParser(date.split(" - ")[1]) }.getOrNull() ?: 0L

    override fun getGenreList() = listOf(
        Genre("16+", 1),
        Genre("18+", 2),
        Genre("Action", 3),
        Genre("Adult", 4),
        Genre("Adventure", 5),
        Genre("Anime", 6),
        Genre("Comedy", 7),
        Genre("Comic", 8),
        Genre("Doujinshi", 9),
        Genre("Drama", 10),
        Genre("Ecchi", 11),
        Genre("Fantasy", 13),
        Genre("Full màu", 14),
        Genre("Game", 15),
        Genre("Gender Bender", 16),
        Genre("Harem", 17),
        Genre("Historical", 18),
        Genre("Horror", 19),
        Genre("Isekai/Dị giới/Trọng sinh", 20),
        Genre("Josei", 21),
        Genre("Live action", 22),
        Genre("Magic", 23),
        Genre("Manga", 24),
        Genre("Manhua", 25),
        Genre("Manhwa", 26),
        Genre("Martial Arts", 27),
        Genre("Mature", 28),
        Genre("Mecha", 29),
        Genre("Mystery", 30),
        Genre("Nấu Ăn", 31),
        Genre("Ngôn Tình", 32),
        Genre("NTR", 33),
        Genre("One shot", 34),
        Genre("Psychological", 35),
        Genre("Romance", 36),
        Genre("School Life", 37),
        Genre("Sci-fi", 38),
        Genre("Seinen", 39),
        Genre("Shoujo", 40),
        Genre("Shoujo Ai", 41),
        Genre("Shounen", 42),
        Genre("Shounen Ai", 43),
        Genre("Slice of life", 44),
        Genre("Smut", 45),
        Genre("Soft Yaoi", 46),
        Genre("Soft Yuri", 47),
        Genre("Sports", 48),
        Genre("Supernatural", 49),
        Genre("Tạp chí truyện tranh", 50),
        Genre("Tragedy", 51),
        Genre("Trap (Crossdressing)", 52),
        Genre("Trinh Thám", 53),
        Genre("Truyện scan", 54),
        Genre("Tu chân - tu tiên", 55),
        Genre("VnComic", 56),
        Genre("Webtoon", 57),
        Genre("Yuri", 58),
    )
}
