package eu.kanade.tachiyomi.multisrc.madara

import generator.ThemeSourceData.MultiLang
import generator.ThemeSourceData.SingleLang
import generator.ThemeSourceGenerator

class MadaraGenerator : ThemeSourceGenerator {

    override val themePkg = "madara"

    override val themeClass = "Madara"

    override val baseVersionCode: Int = 20

    override val sources = listOf(
        MultiLang("Leviatan Scans", "https://leviatanscans.com", listOf("en", "es"), className = "LeviatanScansFactory", overrideVersionCode = 9),
        MultiLang("MangaForFree.net", "https://mangaforfree.net", listOf("en", "ko", "all"), isNsfw = true, className = "MangaForFreeFactory", pkgName = "mangaforfree", overrideVersionCode = 1),
        MultiLang("Manhwa18.cc", "https://manhwa18.cc", listOf("en", "ko", "all"), isNsfw = true, className = "Manhwa18CcFactory", pkgName = "manhwa18cc", overrideVersionCode = 2),
        MultiLang("Reaper Scans", "https://reaperscans.com", listOf("en", "pt-BR", "fr", "id", "tr"), className = "ReaperScansFactory", pkgName = "reaperscans", overrideVersionCode = 5),
        MultiLang("Seven King Scanlation", "https://sksubs.net", listOf("es", "en"), isNsfw = true),
        MultiLang("YugenMangas", "https://yugenmangas.com", listOf("es", "pt-BR"), overrideVersionCode = 2),
        SingleLang("1st Kiss Manga.love", "https://1stkissmanga.love", "en", className = "FirstKissMangaLove", overrideVersionCode = 1),
        SingleLang("1st Kiss Manhua", "https://1stkissmanhua.com", "en", className = "FirstKissManhua", overrideVersionCode = 3),
        SingleLang("1st Kiss", "https://1stkissmanga.io", "en", className = "FirstKissManga", pkgName = "firstkissmanga", overrideVersionCode = 7),
        SingleLang("1stKissManga.Club", "https://1stkissmanga.club", "en", className = "FirstKissMangaClub", overrideVersionCode = 1),
        SingleLang("247Manga", "https://247manga.com", "en", className = "Manga247", overrideVersionCode = 1),
        SingleLang("24hManga", "https://24hmanga.com", "en", isNsfw = true, className = "TwentyFourhManga"),
        SingleLang("24hRomance", "https://24hromance.com", "en", className = "Romance24h"),
        SingleLang("365Manga", "https://365manga.com", "en", className = "ThreeSixtyFiveManga", overrideVersionCode = 1),
        SingleLang("8Muses Comics", "https://8muses.love/", "en", isNsfw = true, className = "EightMusesComics"),
        SingleLang("AZManhwa", "https://azmanhwa.net", "en"),
        SingleLang("Adonis Fansub", "https://manga.adonisfansub.com", "tr", overrideVersionCode = 1),
        SingleLang("Adult Webtoon", "https://adultwebtoon.com/", "en", isNsfw = true),
        SingleLang("Adult Painful Nightz", "https://adults.painfulnightz.com", "en", isNsfw = true),
        SingleLang("Agent of Change Translations", "https://aoc.moe", "en", overrideVersionCode = 1),
        SingleLang("Aiin Scan", "https://aiinscan.xyz", "pt-BR"),
        SingleLang("AiYuManga", "https://aiyumangascanlation.com", "es"),
        SingleLang("AkuManga", "https://akumanga.com", "ar", overrideVersionCode = 1),
        SingleLang("Akuma no Tenshi", "https://akumanotenshi.com", "pt-BR", className = "AkumaNoTenshi"),
        SingleLang("AllPornComic", "https://allporncomic.com", "en", isNsfw = true),
        SingleLang("AllTopManga", "https://alltopmanga.com", "en", isNsfw = true),
        SingleLang("Anikiga", "https://anikiga.com", "tr"),
        SingleLang("Anime Center Scan", "https://animecenterscan.com", "pt-BR", isNsfw = true),
        SingleLang("Anisa Manga", "https://anisamanga.com", "tr"),
        SingleLang("ApollComics", "https://apollcomics.xyz", "es", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Apolltoons", "https://apolltoons.xyz", "es", isNsfw = true),
        SingleLang("Aqua Manga", "https://aquamanga.com", "en"),
        SingleLang("ArazNovel", "https://www.araznovel.com", "tr", overrideVersionCode = 3),
        SingleLang("Arthur Scan", "https://arthurscan.xyz", "pt-BR", overrideVersionCode = 4),
        SingleLang("Astral Library", "https://www.astrallibrary.net", "en", overrideVersionCode = 2),
        SingleLang("Asura Raw", "https://asuraraw.com", "en", overrideVersionCode = 1),
        SingleLang("Atikrost", "https://atikrost.com", "tr", overrideVersionCode = 1),
        SingleLang("Azora", "https://azoraworld.com", "ar", overrideVersionCode = 3),
        SingleLang("BL Manhwa Club", "https://blmanhwa.club", "pt-BR", isNsfw = true, className = "BlManhwaClub", overrideVersionCode = 2),
        SingleLang("Bakaman", "https://bakaman.net", "th", overrideVersionCode = 1),
        SingleLang("Banana Cítrica", "https://dinastiacilly.com", "pt-BR", isNsfw = true, pkgName = "bananamecanica", className = "BananaCitrica", overrideVersionCode = 4),
        SingleLang("BestManga", "https://bestmanga.club", "ru", overrideVersionCode = 1),
        SingleLang("BestManhua", "https://bestmanhua.com", "en", overrideVersionCode = 2),
        SingleLang("Block Manga", "https://blockmanga.com", "en", overrideVersionCode = 1),
        SingleLang("BlogManga", "https://blogmanga.net", "en"),
        SingleLang("Boruto Explorer", "https://leitor.borutoexplorer.com.br", "pt-BR", overrideVersionCode = 1),
        SingleLang("BoysLove", "https://boyslove.me", "en", overrideVersionCode = 2),
        SingleLang("CAT-translator", "https://cat-translator.com", "th", className = "CatTranslator", overrideVersionCode = 1),
        SingleLang("Café com Yaoi", "http://cafecomyaoi.com.br", "pt-BR", pkgName = "cafecomyaoi", className = "CafeComYaoi", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Cat300", "https://cat300.com", "th", isNsfw = true, className = "Cat300", overrideVersionCode = 1),
        SingleLang("CatOnHeadTranslations", "https://catonhead.com", "en", overrideVersionCode = 2),
        SingleLang("Cerise Scans", "https://cerisescans.com", "pt-BR", overrideVersionCode = 2),
        SingleLang("Chibi Manga", "https://www.cmreader.info", "en", overrideVersionCode = 1),
        SingleLang("Clover Manga", "https://clover-manga.com", "tr", overrideVersionCode = 2),
        SingleLang("Colored Manga", "https://coloredmanga.com", "en", overrideVersionCode = 1),
        SingleLang("ComicKiba", "https://comickiba.com", "en", overrideVersionCode = 1),
        SingleLang("Comicdom", "https://comicdom.org", "en", overrideVersionCode = 2),
        SingleLang("Comics Valley", "https://comicsvalley.com", "hi", isNsfw = true, overrideVersionCode = 1),
        SingleLang("ComicsWorld", "https://comicsworld.in", "hi"),
        SingleLang("Comictoon", "https://comictoonthaith-new.com", "th", isNsfw = true),
        SingleLang("Cookie Kiara", "https://18.kiara.cool", "en", isNsfw = true),
        SingleLang("CopyPasteScan", "https://copypastescan.xyz", "es", overrideVersionCode = 1),
        SingleLang("Cronos Scan", "https://cronosscan.net", "pt-BR", overrideVersionCode = 1),
        SingleLang("DarkYue Realm", "https://darkyuerealm.site/web", "pt-BR", pkgName = "darkyurealm", overrideVersionCode = 4),
        SingleLang("Decadence Scans", "https://reader.decadencescans.com", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("DiamondFansub", "https://diamondfansub.com", "tr", overrideVersionCode = 1),
        SingleLang("Disaster Scans", "https://disasterscans.com", "en", overrideVersionCode = 2),
        SingleLang("Diskus Scan", "https://diskusscan.com", "pt-BR", overrideVersionCode = 1),
        SingleLang("DokkoManga", "https://dokkomanga.xyz", "es"),
        SingleLang("DoujinHentai", "https://doujinhentai.net", "es", isNsfw = true, overrideVersionCode = 1),
        SingleLang("DragonTranslation", "https://dragontranslation.com", "es", isNsfw = true, overrideVersionCode = 4),
        SingleLang("Drake Scans", "https://drakescans.com", "en"),
        SingleLang("Dream Manga", "https://www.swarmmanga.com", "en", overrideVersionCode = 3),
        SingleLang("Dream Union Scan", "https://www.dreamunionscan.com", "pt-BR", overrideVersionCode = 2),
        SingleLang("Drope Scan", "https://dropescan.com", "pt-BR", overrideVersionCode = 4),
        SingleLang("EGY Manga", "https://egymanga.net", "ar", overrideVersionCode = 1),
        SingleLang("Empire Webtoon", "https://webtoonempire.com", "ar", isNsfw = true),
        SingleLang("Eromanhwas", "https://eromanhwas.com", "en"),
        SingleLang("Esomanga", "http://esomanga.com", "tr"),
        SingleLang("Eternal Scans", "https://eternalscans.com", "en"),
        SingleLang("Estufa de Cristal", "https://scanestufadecristal.site", "pt-BR", className = "EstufaDeCristal"),
        SingleLang("FDM Scan", "https://fdmscan.com", "pt-BR", overrideVersionCode = 3),
        SingleLang("FaeStorm", "https://faestormmanga.com", "tr"),
        SingleLang("FastManhwa", "https://fastmanhwa.net", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Final Scans", "https://finalscans.com", "pt-BR", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Fiz Manga", "https://fizmanga.com", "en"),
        SingleLang("Fleur Blanche", "https://fbsquadz.com", "pt-BR", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Fox White", "https://foxwhite.com.br", "pt-BR"),
        SingleLang("Free Manga", "https://freemanga.me", "en", isNsfw = true, overrideVersionCode = 3),
        SingleLang("FreeWebtoonCoins", "https://freewebtooncoins.com", "en", overrideVersionCode = 1),
        SingleLang("Fug Manga", "https://fugmanga.net", "ar", overrideVersionCode = 1),
        SingleLang("Fukushuu no Yuusha", "https://fny-scantrad.com", "fr", overrideVersionCode = 2),
        SingleLang("Furio Scans", "https://furioscans.com", "pt-BR", overrideVersionCode = 4),
        SingleLang("GalaxyDegenScans", "https://gdstmp.site", "en", overrideVersionCode = 3),
        SingleLang("Gatemanga", "https://gatemanga.com", "ar", overrideVersionCode = 1),
        SingleLang("Gemanga", "https://gemanga.com", "ar", overrideVersionCode = 2),
        SingleLang("Glass Sky", "https://glasscan.online", "pt-BR"),
        SingleLang("Gogoscans", "https://www.gogoscans.com", "en"),
        SingleLang("Goof Fansub", "https://gooffansub.com", "pt-BR", isNsfw = true),
        SingleLang("GuncelManga", "https://guncelmanga.com", "tr", overrideVersionCode = 1),
        SingleLang("HM2D", "https://mangadistrict.com/hdoujin", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Hades no Fansub Hentai", "https://h.mangareaderpro.com", "es", isNsfw = true),
        SingleLang("Hades no Fansub", "https://mangareaderpro.com/es", "es"),
        SingleLang("Harimanga", "https://harimanga.com", "en", overrideVersionCode = 1),
        SingleLang("Hattori Manga", "https://hattorimanga.com", "tr", isNsfw = true),
        SingleLang("Hayalistic", "https://hayalistic.com", "tr"),
        SingleLang("Hentai CB", "https://hentaicb.top", "vi", isNsfw = true, overrideVersionCode = 1, pkgName = "hentaicube"),
        SingleLang("Hentai Manga", "https://hentaimanga.me", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Hentai Teca", "https://hentaiteca.net", "pt-BR", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Hentai20", "https://hentai20.com", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("HentaiRead", "https://hentairead.com", "en", isNsfw = true, className = "Hentairead", overrideVersionCode = 2),
        SingleLang("HentaiWebtoon", "https://hentaiwebtoon.com", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("HentaiXComic", "https://hentaixcomic.com", "en", isNsfw = true),
        SingleLang("HentaiXYuri", "https://hentaixyuri.com", "en", isNsfw = true),
        SingleLang("HentaiZone", "https://hentaizone.xyz", "fr", isNsfw = true),
        SingleLang("Hentaidexy", "https://hentaidexy.com", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Heroz Scanlation", "https://herozscans.com", "en", overrideVersionCode = 1),
        SingleLang("Hiperdex", "https://hiperdex.com", "en", isNsfw = true, overrideVersionCode = 5),
        SingleLang("Hizomanga", "https://hizomanga.com", "ar", overrideVersionCode = 1),
        SingleLang("Hscans", "https://hscans.com", "en", overrideVersionCode = 2),
        SingleLang("Hunter Fansub", "https://hunterfansub.com", "es", overrideVersionCode = 1),
        SingleLang("Hunters Scan", "https://huntersscan.xyz", "pt-BR", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Ichirin No Hana Yuri", "https://ichirinnohanayuri.com.br", "pt-BR", overrideVersionCode = 3),
        SingleLang("Ikifeng", "https://ikifeng.com", "es", isNsfw = true),
        SingleLang("Immortal Updates", "https://immortalupdates.com", "en", overrideVersionCode = 2),
        SingleLang("Império Scans", "https://imperioscans.com.br", "pt-BR", className = "ImperioScans", overrideVersionCode = 1),
        SingleLang("InfraFandub", "https://infrafandub.xyz", "es"),
        SingleLang("Inmortal Scan", "https://manga.mundodrama.site", "es"),
        SingleLang("InstaManhwa", "https://www.instamanhwa.com", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("IsekaiScan.com", "https://isekaiscan.com", "en", className = "IsekaiScanCom", overrideVersionCode = 4),
        SingleLang("IsekaiScan.eu (unoriginal)", "https://isekaiscan.eu", "en", className = "IsekaiscanEu"),
        SingleLang("IsekaiScanManga (unoriginal)", "https://isekaiscanmanga.com", "en", className = "IsekaiScanManga", overrideVersionCode = 1),
        SingleLang("Its Your Right Manhua", "https://itsyourightmanhua.com", "en", className = "ItsYourRightManhua", overrideVersionCode = 2),
        SingleLang("JaiminisBox.net", "https://jaiminisbox.net", "en", className = "Jaiminisboxnet"),
        SingleLang("Jiangzaitoon", "https://jiangzaitoon.biz", "tr", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Jiro Comics", "https://jirocomics.com", "en", isNsfw = true),
        SingleLang("Kami Sama Explorer", "https://leitor.kamisama.com.br", "pt-BR", overrideVersionCode = 2),
        SingleLang("KawaScans", "https://kawascans.com", "en", overrideVersionCode = 1),
        SingleLang("Kiara", "https://kiara.cool", "en"),
        SingleLang("KisekiManga", "https://kisekimanga.com", "en", overrideVersionCode = 1),
        SingleLang("Kissmanga.in", "https://kissmanga.in", "en", className = "KissmangaIn", overrideVersionCode = 2),
        SingleLang("KlikManga", "https://klikmanga.id", "id", overrideVersionCode = 2),
        SingleLang("Kokomanga", "https://kokomanga.com", "en"),
        SingleLang("Kun Manga", "https://kunmanga.com", "en", overrideVersionCode = 1),
        SingleLang("LHTranslation", "https://lhtranslation.net", "en", overrideVersionCode = 1),
        SingleLang("Lara Manga", "https://laramanga.com", "en"),
        SingleLang("Latest Manga", "https://latestmanga.net", "en", overrideVersionCode = 1),
        SingleLang("Levelerscans", "https://levelerscans.xyz", "en", overrideVersionCode = 1),
        SingleLang("Leviatan Scans X", "https://xxx.leviatanscans.com", "en", isNsfw = true),
        SingleLang("Lily Manga", "https://lilymanga.com", "en"),
        SingleLang("Lima Scans", "http://limascans.xyz/v2", "pt-BR", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Little Monster Scan", "https://littlemonsterscan.com.br", "pt-BR", overrideVersionCode = 4),
        SingleLang("Lolicon", "https://lolicon.mobi", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Lord Manga", "https://lordmanga.com", "en"),
        SingleLang("LovableSubs", "https://lovablesubs.com", "tr", overrideVersionCode = 1),
        SingleLang("Lumine Scans", "https://luminescans.xyz", "en", overrideVersionCode = 1),
        SingleLang("MG Komik", "https://mgkomik.com", "id", overrideVersionCode = 2),
        SingleLang("MHentais", "https://mhentais.com", "pt-BR", isNsfw = true, overrideVersionCode = 1),
        SingleLang("MMScans", "https://mm-scans.org", "en", overrideVersionCode = 2),
        SingleLang("MadaraDex", "https://madaradx.org", "en", isNsfw = true),
        SingleLang("Manga Action", "https://mangaaction.com", "en", overrideVersionCode = 2),
        SingleLang("Manga Bin", "https://mangabin.com", "en", overrideVersionCode = 1),
        SingleLang("Manga Chill", "https://mangachill.love", "en", overrideVersionCode = 4),
        SingleLang("Manga Crab", "https://mangacrab.com", "es", overrideVersionCode = 1),
        SingleLang("Manga District", "https://mangadistrict.com", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Manga Diyari", "https://manga-diyari.com", "tr", overrideVersionCode = 2),
        SingleLang("Manga Drop Out", "https://www.mangadropout.xyz", "id", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Manga Fenix", "https://manga-fenix.com", "es", overrideVersionCode = 2),
        SingleLang("Manga Funny", "https://mangafunny.com", "en"),
        SingleLang("Manga Gohan", "https://gokumanga.com/", "ja", overrideVersionCode = 1),
        SingleLang("Manga Hane", "https://manga-hane.com", "tr"),
        SingleLang("Manga Hentai", "https://mangahentai.me", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Manga Hero", "https://mangahero.xyz", "en", overrideVersionCode = 2),
        SingleLang("Manga Keyfi", "https://mangakeyfi.net", "tr"),
        SingleLang("Manga Kio", "https://mangakio.com", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Manga Kiss", "https://mangakiss.org", "en", overrideVersionCode = 1),
        SingleLang("Manga Leveling", "https://mangaleveling.com", "en"),
        SingleLang("Manga Lord", "https://mangalord.com", "en", overrideVersionCode = 1),
        SingleLang("Manga Mitsu", "https://mangamitsu.com", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Manga Mix", "https://mangamix.me", "ar", overrideVersionCode = 1),
        SingleLang("Manga Online Team", "https://mangaonlineteam.com", "en"),
        SingleLang("Manga Oubarab", "https://mangaoubarab.com", "ar", overrideVersionCode = 1),
        SingleLang("Manga Queen", "https://mangaqueen.net", "en"),
        SingleLang("Manga Read", "https://mangaread.co", "en", overrideVersionCode = 1),
        SingleLang("Manga Riki", "https://mangariki.com", "en"),
        SingleLang("Manga Rock Team", "https://mangarockteam.com", "en", overrideVersionCode = 1),
        SingleLang("Manga Rocky", "https://mangarocky.com", "en", overrideVersionCode = 1),
        SingleLang("Manga SY", "https://www.mangasy.com", "en", overrideVersionCode = 1),
        SingleLang("Manga Şehri", "https://mangasehri.com", "tr", className = "MangaSehri", isNsfw = true),
        SingleLang("Manga Sepeti", "https://www.mangasepeti.com", "tr"),
        SingleLang("Manga Sky", "https://mangasky.net", "en"),
        SingleLang("Manga Starz", "https://mangastarz.com", "ar", overrideVersionCode = 1),
        SingleLang("Manga Too", "https://mangatoo.com", "en", overrideVersionCode = 1),
        SingleLang("Manga Weeaboo", "https://mangaweeaboo.com", "en", overrideVersionCode = 1),
        SingleLang("Manga Weebs", "https://mangaweebs.in", "en", overrideVersionCode = 6),
        SingleLang("Manga Weed", "https://mangaweed.com", "en", overrideVersionCode = 2),
        SingleLang("Manga-Online.co", "https://www.manga-online.co", "th", className = "MangaOnlineCo"),
        SingleLang("Manga-Scantrad", "https://manga-scantrad.net", "fr", className = "MangaScantrad", overrideVersionCode = 2),
        SingleLang("Manga-TX", "https://manga-tx.com", "en", className = "Mangatxunoriginal"),
        SingleLang("Manga-fast.com", "https://manga-fast.com", "en", className = "Mangafastcom", overrideVersionCode = 3),
        SingleLang("Manga18 Fx", "https://manga18fx.com", "en", overrideVersionCode = 1),
        SingleLang("Manga1st", "https://manga1st.com", "en", overrideVersionCode = 2),
        SingleLang("Manga1st.online", "https://manga1st.online", "en", className = "MangaFirstOnline", overrideVersionCode = 1),
        SingleLang("Manga347", "https://manga347.com", "en", overrideVersionCode = 3),
        SingleLang("Manga3S", "https://manga3s.com", "en", overrideVersionCode = 4),
        SingleLang("Manga47", "https://manga47.net", "en", overrideVersionCode = 1),
        SingleLang("Manga4All", "https://manga4all.net", "en", overrideVersionCode = 3),
        SingleLang("Manga68", "https://manga68.com", "en", overrideVersionCode = 1),
        SingleLang("Manga68.net", "https://manga68.net", "en", className = "Manga68net"),
        SingleLang("MangaBaz", "https://mangabaz.net", "en"),
        SingleLang("MangaBob", "https://mangabob.com", "en", overrideVersionCode = 1),
        SingleLang("MangaBoss", "https://mangaboss.org", "en"),
        SingleLang("MangaBox", "https://mangabox.org", "en"),
        SingleLang("MangaCC", "https://mangacc.com", "en"),
        SingleLang("MangaCV", "https://mangacv.com", "en", isNsfw = true),
        SingleLang("MangaClash", "https://mangaclash.com", "en", overrideVersionCode = 3),
        SingleLang("MangaCultivator", "https://mangacultivator.com", "en", overrideVersionCode = 2),
        SingleLang("MangaDeemak", "https://mangadeemak.com", "th"),
        SingleLang("MangaDods", "https://www.mangadods.com", "en", overrideVersionCode = 2),
        SingleLang("MangaDol", "https://mangadol.com", "en"),
        SingleLang("MangaDrago", "https://mangadrago.com", "en"),
        SingleLang("MangaEffect", "https://mangaeffect.com", "en", overrideVersionCode = 1),
        SingleLang("MangaFort", "https://mangafort.com", "en", overrideVersionCode = 1),
        SingleLang("MangaFoxFull", "https://mangafoxfull.com", "en"),
        SingleLang("MangaGG", "https://mangagg.com", "en", overrideVersionCode = 2),
        SingleLang("MangaGreat", "https://mangagreat.com", "en", overrideVersionCode = 3),
        SingleLang("MangaHZ", "https://www.mangahz.com", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("MangaKitsune", "https://mangakitsune.com", "en", isNsfw = true, overrideVersionCode = 4),
        SingleLang("MangaKomi", "https://mangakomi.com", "en", overrideVersionCode = 4),
        SingleLang("MangaLime", "https://mangalime.com", "en"),
        SingleLang("MangaLionz", "https://mangalionz.com", "ar"),
        SingleLang("MangaMG", "https://mangamg.com", "en"),
        SingleLang("MangaManhua", "https://mangamanhua.online", "en", overrideVersionCode = 1),
        SingleLang("MangaManiacs", "https://mangamaniacs.org", "en", isNsfw = true),
        SingleLang("MangaMe", "https://mangame.org", "en", overrideVersionCode = 1),
        SingleLang("MangaMoli", "https://mangamoli.com", "en"),
        SingleLang("MangaPT", "https://mangapt.com", "es", isNsfw = true),
        SingleLang("MangaRabic", "https://mangarabic.com", "ar"),
        SingleLang("MangaRead.org", "https://www.mangaread.org", "en", className = "MangaReadOrg", overrideVersionCode = 1),
        SingleLang("MangaRex", "https://mangarex.co", "en"),
        SingleLang("MangaSco", "https://mangasco.com", "en", overrideVersionCode = 1),
        SingleLang("MangaSmile", "https://mangasmile.com", "en", overrideVersionCode = 1),
        SingleLang("MangaSpark", "https://mangaspark.com", "ar", overrideVersionCode = 1),
        SingleLang("MangaStic", "https://mangastic.com", "en"),
        SingleLang("MangasTK", "https://mangastk.com", "es", isNsfw = true),
        SingleLang("MangaTK", "https://mangatk.com", "en"),
        SingleLang("MangaTX", "https://mangatx.com", "en", overrideVersionCode = 1),
        SingleLang("MangaToRead", "https://mangatoread.com", "en"),
        SingleLang("MangaTone", "https://mangatone.com", "en"),
        SingleLang("MangaTop1", "https://mangatop1.com", "en"),
        SingleLang("MangaTuli", "https://mangatuli.com", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("MangaUS", "https://mangaus.xyz", "en", overrideVersionCode = 2),
        SingleLang("MangaWT", "https://mangawt.com", "tr", overrideVersionCode = 1),
        SingleLang("MangaWise", "https://mangawise.com", "en"),
        SingleLang("MangaX1", "https://mangax1.com", "en"),
        SingleLang("MangaX18", "https://mangax18.com", "en", isNsfw = true),
        SingleLang("MangaXP", "https://mangaxp.com", "en", overrideVersionCode = 1),
        SingleLang("MangaYami", "https://www.mangayami.club", "en", overrideVersionCode = 2),
        SingleLang("Mangaforfree.com", "https://mangaforfree.com", "en", isNsfw = true, className = "Mangaforfreecom"),
        SingleLang("Mangaka3rb", "https://mangaka3rb.com", "ar"),
        SingleLang("Mangakik", "https://mangakik.com", "en"),
        SingleLang("Manganato.info", "https://manganato.info", "en", className = "Manganatoinfo"),
        SingleLang("Mangas Origines X", "https://x.mangas-origines.fr", "fr", isNsfw = true),
        SingleLang("Mangas Origines", "https://mangas-origines.fr", "fr", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Mangas18", "https://mangas18.com", "en"),
        SingleLang("Mangasushi", "https://mangasushi.net", "en", overrideVersionCode = 2),
        SingleLang("Mangauptocats", "https://mangauptocats.online", "th", overrideVersionCode = 2),
        SingleLang("Mangazuki.me", "https://mangazuki.me", "en", className = "MangazukiMe", overrideVersionCode = 1),
        SingleLang("Mangceh", "https://mangceh.me", "id", isNsfw = true, overrideVersionCode = 3),
        SingleLang("Manhatic", "https://manhatic.com", "ar", isNsfw = true),
        SingleLang("Manhua Dragon", "https://manhuadragon.com", "en"),
        SingleLang("Manhua ES", "https://manhuaes.com", "en", overrideVersionCode = 6),
        SingleLang("Manhua Plus", "https://manhuaplus.com", "en", overrideVersionCode = 6),
        SingleLang("Manhua SY", "https://www.manhuasy.com", "en", overrideVersionCode = 1),
        SingleLang("ManhuaBox", "https://manhuabox.net", "en", overrideVersionCode = 2),
        SingleLang("ManhuaChill", "https://manhuachill.com", "en"),
        SingleLang("Mangacim", "https://www.mangacim.com", "tr"),
        SingleLang("ManhuaComic", "https://manhuacomic.com", "en"),
        SingleLang("ManhuaDex", "https://manhuadex.com", "en", overrideVersionCode = 1),
        SingleLang("ManhuaFast", "https://manhuafast.com", "en", overrideVersionCode = 1),
        SingleLang("ManhuaHot", "https://manhuahot.com", "en"),
        SingleLang("ManhuaPro", "https://manhuapro.com", "en", overrideVersionCode = 2),
        SingleLang("ManhuaToon", "https://manhuatoon.com", "en"),
        SingleLang("ManhuaUS", "https://manhuaus.com", "en", overrideVersionCode = 5),
        SingleLang("ManhuaZone", "https://manhuazone.com", "en"),
        SingleLang("Manhuaga", "https://manhuaga.com", "en", overrideVersionCode = 2),
        SingleLang("Manhualo", "https://manhualo.com", "en", overrideVersionCode = 1),
        SingleLang("Manhuas.net", "https://manhuas.net", "en", className = "Manhuasnet", overrideVersionCode = 2),
        SingleLang("Manhwa Chill", "https://manhwachill.com", "en"),
        SingleLang("Manhwa Raw", "https://manhwaraw.com", "ko", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Manhwa.biz", "https://manhwa.biz", "en", isNsfw = true, className = "Manhwabiz"),
        SingleLang("Manhwa18.app", "https://manhwa18.app", "en", isNsfw = true, className = "Manhwa18app"),
        SingleLang("Manhwa18.org", "https://manhwa18.org", "en", isNsfw = true, className = "Manhwa18Org", overrideVersionCode = 2),
        SingleLang("Manhwa365", "https://manhwa365.com", "en", isNsfw = true),
        SingleLang("Manhwa68", "https://manhwa68.com", "en", isNsfw = true, overrideVersionCode = 3),
        SingleLang("ManhwaBookShelf", "https://manhwabookshelf.com", "en"),
        SingleLang("ManhwaClan", "https://manhwaclan.com", "en"),
        SingleLang("ManhwaNelo", "https://manhwanelo.com", "en", overrideVersionCode = 2),
        SingleLang("ManhwaTime", "https://manhwatime.com", "ar"),
        SingleLang("ManhwaWorld", "https://manhwaworld.com", "en"),
        SingleLang("ManhwaXZ", "https://manhwaxz.com", "en"),
        SingleLang("Manhwafull", "https://manhwafull.com", "en", overrideVersionCode = 1),
        SingleLang("Manhwahentai.me", "https://manhwahentai.me", "en", className = "ManhwahentaiMe", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Manhwaraw.net", "https://manhwaraw.net", "en", className = "Manhwarawnet"),
        SingleLang("Manhwatop", "https://manhwatop.com", "en", overrideVersionCode = 2),
        SingleLang("Manhwua.fans", "https://manhwua.fans", "en", isNsfw = true, className = "Manhwuafans"),
        SingleLang("ManyComic", "https://manycomic.com", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("ManyToon", "https://manytoon.com", "en", isNsfw = true, overrideVersionCode = 4),
        SingleLang("ManyToon.me", "https://manytoon.me", "en", isNsfw = true, className = "ManyToonMe", overrideVersionCode = 4),
        SingleLang("ManyToonClub", "https://manytoon.club", "ko", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Mark Scans", "https://markscans.online", "pt-BR", overrideVersionCode = 3),
        SingleLang("Meraki Scan", "https://meraki801.com", "es", isNsfw = true),
        SingleLang("Mhmanga", "https://mhmanga.com", "en"),
        SingleLang("Midnight Mess Scans", "https://midnightmess.org", "en", isNsfw = true, overrideVersionCode = 6),
        SingleLang("Milftoon", "https://milftoon.xxx", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("MiniTwo Scan", "https://minitwoscan.com", "pt-BR"),
        SingleLang("Mirad Scanlator", "https://miradscanlator.site", "pt-BR", overrideVersionCode = 1),
        SingleLang("Mixed Manga", "https://mixedmanga.com", "en", overrideVersionCode = 1),
        SingleLang("Momo no Hana Scan", "https://momonohanascan.com", "pt-BR", className = "MomoNoHanaScan", overrideVersionCode = 1),
        SingleLang("MonarcaManga", "https://monarcamanga.com", "es"),
        SingleLang("Mortals Groove", "https://mortalsgroove.com", "en", overrideVersionCode = 1),
        SingleLang("Muctau", "https://muctau.com", "en", overrideVersionCode = 1),
        SingleLang("MyKomiks", "https://mykomiks.fun", "en", overrideVersionCode = 2),
        SingleLang("Mystical Merries", "https://mysticalmerries.com", "en", overrideVersionCode = 2),
        SingleLang("NeatManga", "https://neatmanga.com", "en", overrideVersionCode = 2),
        SingleLang("NekoBreaker Scan", "https://nekobreakerscan.com", "pt-BR", overrideVersionCode = 1),
        SingleLang("NekoScan", "https://nekoscan.com", "en", overrideVersionCode = 2),
        SingleLang("Neox Scanlator", "https://neoxscans.net", "pt-BR", overrideVersionCode = 11),
        SingleLang("Night Comic", "https://www.nightcomic.com", "en", overrideVersionCode = 1),
        SingleLang("Niji Translations", "https://niji-translations.com", "ar", overrideVersionCode = 1),
        SingleLang("Ninja Scan", "https://ninjascan.xyz", "pt-BR", overrideVersionCode = 1),
        SingleLang("Nitro Scans", "https://nitroscans.com", "en"),
        SingleLang("NovelMic", "https://novelmic.com", "en", overrideVersionCode = 1),
        SingleLang("Novels Town", "https://novelstown.cyou", "ar"),
        SingleLang("Oh No Manga", "https://ohnomanga.com", "en", isNsfw = true),
        SingleLang("Okamishi Scans", "https://geassscan.net", "pt-BR", pkgName = "geassscanlator", overrideVersionCode = 5),
        SingleLang("Olympus Scanlation", "https://olympusscanlation.com", "es"),
        SingleLang("Ow Scan", "https://owscan.com", "pt-BR", overrideVersionCode = 1),
        SingleLang("Paean Scans", "https://paeanscans.com", "en", overrideVersionCode = 1),
        SingleLang("Painful Nightz Scan", "https://painfulnightz.com", "en", overrideVersionCode = 1),
        SingleLang("Petrotechsociety", "https://www.petrotechsociety.org", "en", isNsfw = true),
        SingleLang("Platinum Crown", "https://platinumscans.com", "en", overrideVersionCode = 1),
        SingleLang("PoManga", "https://pomanga.com", "en"),
        SingleLang("Pojok Manga", "https://pojokmanga.com", "id", overrideVersionCode = 3),
        SingleLang("PornComix", "https://www.porncomixonline.net", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Pornwha", "https://pornwha.com", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Prisma Hentais", "https://prismahentai.com", "pt-BR", isNsfw = true),
        SingleLang("Prisma Scans", "https://prismascans.net", "pt-BR", overrideVersionCode = 2),
        SingleLang("Projeto Scanlator", "https://projetoscanlator.com", "pt-BR", overrideVersionCode = 3),
        SingleLang("Pirulito Rosa", "https://pirulitorosa.site", "pt-BR", isNsfw = true),
        SingleLang("QueensManga ملكات المانجا", "https://queensmanga.com", "ar", className = "QueensManga", overrideVersionCode = 1),
        SingleLang("RagnarokScan", "https://ragnarokscan.com", "es"),
        SingleLang("Random Scan", "https://randomscan.online", "pt-BR", overrideVersionCode = 4),
        SingleLang("Random Translations", "https://randomtranslations.com", "en", overrideVersionCode = 1),
        SingleLang("Raw Mangas", "https://rawmangas.net", "ja", isNsfw = true, overrideVersionCode = 2),
        SingleLang("RawDEX", "https://rawdex.net", "ko", isNsfw = true, overrideVersionCode = 1),
        SingleLang("ReadAdult", "https://readadult.net", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("ReadManhua", "https://readmanhua.net", "en", overrideVersionCode = 2),
        SingleLang("Readers Point", "https://readers-point.space", "en"),
        SingleLang("Remangas", "https://remangas.net", "pt-BR"),
        SingleLang("Remoscans", "https://remoscans.xyz", "en"),
        SingleLang("Renascence Scans (Renascans)", "https://new.renascans.com", "en", className = "RenaScans", overrideVersionCode = 1),
        SingleLang("Reset Scans", "https://reset-scans.com", "en", overrideVersionCode = 5),
        SingleLang("Rh2PlusManga", "https://www.rh2plusmanga.com", "th", overrideVersionCode = 3),
        SingleLang("Rüya Manga", "https://www.ruyamanga.com", "tr", className = "RuyaManga", overrideVersionCode = 1),
        SingleLang("RWBY Scan", "https://rwbyscan.site", "pt-BR", isNsfw = true, className = "RwbyScan"),
        SingleLang("S2Manga", "https://s2manga.com", "en", overrideVersionCode = 1),
        SingleLang("SISI GELAP", "https://sigel.xyz", "id", overrideVersionCode = 3),
        SingleLang("SamuraiScan", "https://samuraiscan.com", "es", overrideVersionCode = 1),
        SingleLang("Sawamics", "https://sawamics.com", "en"),
        SingleLang("Scans Raw", "https://scansraw.com", "en", overrideVersionCode = 1),
        SingleLang("Sdl scans", "https://sdlscans.com", "es", className = "SdlScans"),
        SingleLang("Seafoam Scans", "https://seafoamscans.com", "en", overrideVersionCode = 2),
        SingleLang("Seikou Scans", "https://seikouscans.com", "pt-BR", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Sensaina Yuri", "https://sensainayuri.dropescan.com", "pt-BR", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Shield Manga", "https://shieldmanga.io", "en", overrideVersionCode = 3),
        SingleLang("ShinobiScans", "https://shinobiscans.com", "it"),
        SingleLang("ShoujoHearts", "https://shoujohearts.com", "en", overrideVersionCode = 2),
        SingleLang("SiXiang Scans", "http://www.sixiangscans.com", "en", overrideVersionCode = 1),
        SingleLang("Sinensis", "https://sinensisscan.com", "pt-BR", overrideVersionCode = 2),
        SingleLang("Siyahmelek", "https://siyahmelek.net", "tr", isNsfw = true, overrideVersionCode = 3),
        SingleLang("SkyRaws", "https://skyraws.com", "en", overrideVersionCode = 1),
        SingleLang("Skymanga", "https://skymanga.co", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("Sleeping Knight Scans", "https://skscans.com", "en", overrideVersionCode = 2),
        SingleLang("Sleepy Translations", "https://sleepytranslations.com", "en", overrideVersionCode = 1),
        SingleLang("Smash Scan", "https://smashscan.com.br", "pt-BR", overrideVersionCode = 1),
        SingleLang("SodaScan", "https://sodascan.xyz", "pt-BR", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Solo Leveling", "https://readsololeveling.online", "en"),
        SingleLang("Sugar Babies", "https://sugarbbscan.com", "en", overrideVersionCode = 2),
        SingleLang("Summanga", "https://summanga.com", "en", isNsfw = true),
        SingleLang("Sunshine Butterfly Scans", "https://sunshinebutterflyscan.com", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("SuperManga", "https://supermanga.co", "en"),
        SingleLang("Sweet Time Scan", "https://sweetscan.net", "pt-BR", overrideVersionCode = 2),
        SingleLang("TappyToon.Net", "https://tappytoon.net", "en", className = "Tappytoonnet"),
        SingleLang("Tatakae Scan", "https://tatakaescan.xyz", "pt-BR", isNsfw = true, overrideVersionCode = 1),
        SingleLang("TeenManhua", "https://teenmanhua.com", "en"),
        SingleLang("The Beginning After The End", "https://www.thebeginningaftertheend.fr", "fr"),
        SingleLang("The Guild", "https://theguildscans.com", "en"),
        SingleLang("The Sugar", "https://thesugarscan.com", "pt-BR"),
        SingleLang("TheFluffyHangoutGroup", "https://www.fluffyhangout.club", "en", overrideVersionCode = 2),
        SingleLang("Three Queens Scanlator", "https://tqscan.com.br", "pt-BR", overrideVersionCode = 3),
        SingleLang("Tiempo de webeo", "https://tiempodewebeo.com", "es", className = "TiempoDeWebeo", isNsfw = true),
        SingleLang("Time Naight", "https://timenaight.com", "tr"),
        SingleLang("Todaymic", "https://todaymic.com", "en", overrideVersionCode = 1),
        SingleLang("TonizuToon", "https://tonizutoon.com", "tr", isNsfw = true),
        SingleLang("ToonGod", "https://www.toongod.com", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("ToonMany", "https://toonmany.com", "en", isNsfw = true),
        SingleLang("Toonily", "https://toonily.com", "en", isNsfw = true, overrideVersionCode = 6),
        SingleLang("Toonily.net", "https://toonily.net", "en", isNsfw = true, className = "Toonilynet", overrideVersionCode = 2),
        SingleLang("Top Manhua", "https://topmanhua.com", "en", overrideVersionCode = 1),
        SingleLang("Tortuga Ceviri", "https://tortuga-ceviri.com", "tr"),
        SingleLang("TreeManga", "https://treemanga.com", "en", overrideVersionCode = 1),
        SingleLang("TritiniaScans", "https://tritinia.com", "en", overrideVersionCode = 1),
        SingleLang("TuManga.net", "https://tumanga.net", "es", className = "TuMangaNet"),
        SingleLang("Tumangaonline.site", "https://tumangaonline.site", "es", isNsfw = true, className = "TumangaonlineSite", pkgName = "tumangaonlinesite"),
        SingleLang("Twilight Scans", "https://twilightscans.com", "en", overrideVersionCode = 1),
        SingleLang("Türkçe Manga", "https://turkcemanga.com", "tr", className = "TurkceManga", overrideVersionCode = 2),
        SingleLang("Ultralight Scans", "https://readlight.org", "en"),
        SingleLang("Unemployed Scans", "https://unemployedscans.com", "en", overrideVersionCode = 1),
        SingleLang("Uyuyan Balik", "https://uyuyanbalik.com", "tr", overrideVersionCode = 1),
        SingleLang("Uzay Manga", "https://uzaymanga.com", "tr"),
        SingleLang("Vanguard Bun", "https://vanguardbun.com", "en", overrideVersionCode = 1),
        SingleLang("Vapo Hentai", "http://xxx.vaposcans.com", "pt-BR", isNsfw = true),
        SingleLang("Vapo Scan", "https://vaposcans.com", "pt-BR", overrideVersionCode = 1),
        SingleLang("Visbellum", "https://visbellum.com", "pt-BR", overrideVersionCode = 2),
        SingleLang("WD Scans (Wicked Dragon Scans)", "https://wdscans.com", "en", className = "WDScans"),
        SingleLang("Wakamics", "https://wakamics.net", "en"),
        SingleLang("Wakascan", "https://wakascan.com", "fr", overrideVersionCode = 1),
        SingleLang("Walpurgi Scan", "https://walpurgiscan.altervista.org", "it", overrideVersionCode = 2, className = "WalpurgisScan", pkgName = "walpurgisscan"),
        SingleLang("War Queen Scan", "https://wqscan.com", "pt-BR", overrideVersionCode = 6),
        SingleLang("WebNovel", "https://webnovel.live", "en", className = "WebNovelLive", overrideVersionCode = 3),
        SingleLang("WebToon18", "http://webtoon18.net", "en", isNsfw = true, overrideVersionCode = 2),
        SingleLang("WebToon69", "https://webtoon69.com", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("WebToonily", "https://webtoonily.com", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Webtoon Hatti", "https://webtoonhatti.com", "tr", overrideVersionCode = 1),
        SingleLang("Webtoon TR", "https://webtoon-tr.com", "tr"),
        SingleLang("WebtoonScan", "https://webtoonscan.com", "en", isNsfw = true),
        SingleLang("WebtoonUK", "https://webtoon.uk", "en", overrideVersionCode = 2),
        SingleLang("WebtoonXYZ", "https://www.webtoon.xyz", "en", isNsfw = true, overrideVersionCode = 3),
        SingleLang("WebtoonsTOP", "https://webtoons.top", "en", isNsfw = true),
        SingleLang("Winter Scan", "https://winterscan.com", "pt-BR", overrideVersionCode = 4),
        SingleLang("WoopRead", "https://woopread.com", "en", overrideVersionCode = 1),
        SingleLang("WuxiaWorld", "https://wuxiaworld.site", "en", overrideVersionCode = 1),
        SingleLang("XManga", "https://xmanga.io", "en", isNsfw = true),
        SingleLang("XuN Scans", "https://xunscans.xyz", "en", overrideVersionCode = 3),
        SingleLang("Yaoi Hentai", "https://yaoihentai.me", "en", isNsfw = true),
        SingleLang("Yaoi Toshokan", "https://yaoitoshokan.net", "pt-BR", isNsfw = true, overrideVersionCode = 4),
        SingleLang("Yaoi.mobi", "https://yaoi.mobi", "en", isNsfw = true, className = "YaoiManga", pkgName = "yaoimanga", overrideVersionCode = 4),
        SingleLang("YaoiScan", "https://yaoiscan.com", "en", isNsfw = true),
        SingleLang("YaoiToon", "https://yaoitoon.com", "en", isNsfw = true),
        SingleLang("Yetişkin Rüya Manga", "https://yetiskin.ruyamanga.com", "tr", isNsfw = true, className = "YetiskinRuyaManga"),
        SingleLang("YonaBar", "https://yonabar.net", "ar", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Yuri Verso", "https://yuri.live", "pt-BR", overrideVersionCode = 3),
        SingleLang("Zinmanga", "https://zinmanga.com", "en", overrideVersionCode = 1),
        SingleLang("Zinmanhwa", "https://zinmanhwa.com", "en"),
        SingleLang("ZombieLand Saga Scans", "https://zombiland.com.br", "pt-BR", isNsfw = true),
        SingleLang("ZuttoManga", "https://zuttomanga.com", "en", overrideVersionCode = 1),
        SingleLang("hManhwa", "https://hmanhwa.com", "en", isNsfw = true, overrideVersionCode = 1),
        SingleLang("Çizgi Roman Arşivi", "https://cizgiromanarsivi.com", "tr", className = "CizgiRomanArsivi"),
        SingleLang("شبكة كونان العربية", "https://manga.detectiveconanar.com", "ar", className = "DetectiveConanAr", overrideVersionCode = 2),
        SingleLang("مانجا العاشق", "https://3asq.org", "ar", className = "Manga3asq", overrideVersionCode = 2),
        SingleLang("مانجا عرب تيم Manga Arab Team", "https://mangaarbteam.com", "ar", className = "MangaArabTeam", overrideVersionCode = 1),
        SingleLang("مانجا ليك", "https://mangalek.com", "ar", className = "Mangalek", overrideVersionCode = 1),
        SingleLang("مانجا لينك", "https://mangalink.io", "ar", className = "MangaLinkio", overrideVersionCode = 2),
    )

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            MadaraGenerator().createAll()
        }
    }
}
