package eu.kanade.tachiyomi.extension.all.photos18

import java.util.Locale

fun translate(chinese: String): String {
    if (Locale.getDefault().language == "zh") return chinese
    return when (chinese) {
        // Categories
        "极品美女" -> "Top Beauty"
        "清凉写真" -> "Cool photos"
        "性感激情" -> "Sexy Passion"
        "欧美写真" -> "European and American photos"
        "美女图" -> "Beauty"
        "丝袜美腿" -> "Beautiful Legs in Stockings"
        "亚洲美女" -> "Asian Beauty"
        "素人正妹" -> "Amateur Hottie"
        "欧美美女" -> "European and American Beauties"
        "夜店辣妹" -> "Nightclub Hotties"
        // Keywords
        "美穴" -> "Beautiful pussy"
        "全裸" -> "naked"
        "掰穴" -> "Break the hole"
        "福利姬" -> "Welfare Ji"
        "大尺度" -> "large scale"
        "巨乳" -> "big breasts"
        "大尺度私拍" -> "Large scale private shooting"
        "白虎" -> "white tiger"
        "蠢沫沫" -> "Stupid Momo"
        "小丁" -> "Xiao Ding"
        "外流照片" -> "leaked photos"
        "熟女" -> "MILF"
        "走光" -> "exposed"
        "全裸巨乳" -> "Nude big breasts"
        "自慰" -> "masturbate"
        "明星合成" -> "star synthesis"
        "推女郎" -> "push girl"
        "韩模性交套图" -> "Korean model sex set"
        "裸女" -> "naked girl"
        "私拍" -> "Private shoot"
        "阿朱" -> "Aju"
        "明星裸照" -> "Celebrity nude photos"
        "推特" -> "Twitter"
        "三上悠亚" -> "Mikami Yua"
        "流出" -> "flow out"
        "喵小吉" -> "Meow Xiaoji"
        "肛门" -> "anus"
        "原神" -> "Genshin Impact"
        "偷拍" -> "secretly photographed"
        "水淼" -> "shuimiao"
        "口交" -> "oral sex"
        "王雨纯" -> "Wang Yuchun"
        "人妻" -> "wife"
        "张柏芝艳照门照" -> "Cecilia Cheung Nude Photos Door Photos"
        "超大尺度" -> "Extra large scale"
        "自拍" -> "Selfie"
        "国模大尺度" -> "Large scale national model"
        "明星" -> "star"
        "露穴" -> "exposed hole"
        "雨波" -> "Yubo"
        "古装" -> "Ancient costume"
        "韩大尺度" -> "Korean large scale"
        "姜仁卿" -> "Jiang Renqing"
        "足交" -> "Footjob"
        "露毛" -> "Showing hair"
        "白虎少女" -> "white tiger girl"
        "贫乳" -> "Small breasts"
        "外流" -> "outflow"
        "空姐" -> "Airline stewardess"
        "中出" -> "Creampie"
        "少女" -> "girl"
        "肉便器" -> "meat toilet"
        "明星走光" -> "Star shines"
        "露奶" -> "Showing breasts"
        "美女与狗交配" -> "Beauty and dog mating"
        "旗袍" -> "cheongsam"
        "学生全裸" -> "Students naked"
        "越南" -> "Vietnam"
        "港模" -> "Hong Kong model"
        "一本道" -> "One way"
        "林襄" -> "Lin Xiang"
        "韩国芸能界模特" -> "Korean Yun Neng model"
        "柚木" -> "Teak"
        "自拍外流" -> "Selfies leaked"
        "情趣内衣" -> "Sexy lingerie"
        "波多野结衣" -> "Hatano Yui"
        "肛交" -> "anal sex"
        "无码剧照" -> "Uncoded stills"
        "性交" -> "sexual intercourse"
        "私人玩物" -> "personal plaything"
        "就是阿朱啊" -> "It's A'Zhu"
        "国模啪啪" -> "Chinese model sex"
        "香港" -> "Hongkong"
        "易阳" -> "Yiyang"
        "妲己" -> "Daji"
        "小穴" -> "pussy"
        "舒淇" -> "Shu Qi"
        "美女裸照" -> "Beautiful nude photos"
        "母狗" -> "bitch"
        "野外露出" -> "exposed in the wild"
        "尤妮丝" -> "Eunice"
        "摄影师" -> "photographer"
        "日本超正妹全裸" -> "Japanese super hot girl naked"
        "放尿" -> "urinate"
        "动图" -> "GIF"
        "瑜伽" -> "Yoga"
        "李丽莎" -> "Li Lisa"
        "华模特辑" -> "Chinese models collection"
        "网红" -> "internet celebrity"
        "肛塞" -> "anal plug"
        "陆模" -> "Lu model"
        "糯美子" -> "Nuo Meizi"
        "大奶" -> "big tits"
        "婚纱" -> "Wedding dress"
        "处女" -> "virgin"
        "福利" -> "Welfare"
        "谢忻" -> "Xie Xin"
        "鱼子酱" -> "caviar"
        "抖音" -> "Tik Tok"
        "无马套图流出" -> "Pictures without horses leaked"
        "三上悠亜" -> "Mikami Yua"
        "激凸" -> "convex"
        "唐安琪" -> "Tang Anqi"
        "眼镜" -> "Glasses"
        "百合" -> "lily"
        "正妹全裸" -> "Pretty girl naked"
        "妈妈" -> "Mother"
        "晴儿" -> "Qing'er"
        "校服" -> "Uniforms"
        "桜井宁宁" -> "Sakurai Nene"
        "雪白大奶" -> "snow white big breasts"
        "王馨瑶" -> "Wang Xinyao"
        "健身" -> "fitness"
        "韩国嫩模无圣光大尺度私拍套图" -> "Korean young model Wu Shengguang's large-scale private photoshoot set"
        "乳晕" -> "Areola"
        "汉服" -> "Hanfu"
        "女学生外流裸照" -> "Nude photos of female students leaked"
        "利世" -> "Li Shi"
        "少妇" -> "young woman"
        "香草少女" -> "vanilla girl"
        "陈冠希" -> "Edison Chen"
        "舒淇裸体写真集" -> "Shu Qi nude photo album"
        "星之迟迟" -> "The star is late"
        "人妖" -> "shemale"
        "多毛" -> "hairy"
        "潘多拉" -> "Pandora"
        "缇娜美" -> "Tinami"
        "王语纯" -> "Wang Yuchun"
        "梦心玥" -> "Meng Xinyue"
        "熟女人妻出轨" -> "Mature wife cheats on her"
        "无内" -> "Guilty-free"
        "反差婊" -> "Contrast bitch"
        "内衣" -> "underwear"
        "乳头" -> "nipple"
        "布丁大法" -> "Pudding method"
        "橙子喵酱" -> "orange meow sauce"
        "精液" -> "semen"
        "古风" -> "antiquity"
        "性奴" -> "sex slave"
        "桜桃喵" -> "Sakura peach meow"
        "母乳" -> "breast milk"
        "懂小姐" -> "Understand Miss"
        "怀旧女星" -> "nostalgic actress"
        "神楽坂真冬" -> "Kanamezaka Mafuyu"
        "女同" -> "Lesbian"
        "雪碧露点" -> "Sprite dew point"
        "女明星全裸" -> "Female celebrities naked"
        "陆模私拍" -> "Lu model private shooting"
        "网络收集系列" -> "Network collection series"
        "素人" -> "Amateur"
        "透明" -> "transparent"
        "徐若瑄" -> "Vivian Hsu"
        "无圣光大尺度" -> "Large scale without holy light"
        "秀人" -> "showman"
        "街拍" -> "street photography"
        "完具" -> "Complete"
        "瑜伽裤" -> "yoga pants"
        "果儿" -> "fruit"
        "福利姬大尺度" -> "Welfare Ji large scale"
        "美乳" -> "beautiful breasts"
        "香港明星裸照" -> "Hong Kong celebrity nude photos"
        "洛丽塔" -> "Lolita"
        "高潮" -> "climax"
        "林志玲" -> "Lin Chiling"
        "俄罗斯" -> "Russia"
        "美鲍" -> "Abalone"
        "黄可" -> "Huang Ke"
        "艺人" -> "artist"
        "野外" -> "field"
        "人妻丁丁" -> "Wife penis"
        "外国明星露点" -> "Foreign star exposure points"
        "透视" -> "perspective"
        "一字马" -> "One word horse"
        "黑人" -> "Black person"
        "处女穴" -> "virgin hole"
        "白石茉莉奈" -> "Shiraishi Morina"
        "抖娘利世" -> "Dou Niang Li Shi"
        "早期未成名" -> "Not famous in the early days"
        "白银" -> "silver"
        "刘亦菲" -> "Liu Yifei"
        "情趣" -> "Interesting"
        "后入" -> "After the"
        "魔物喵" -> "monster meow"
        "掰屄" -> "Break your cunt"
        // "性感激情" -> "sexy passion"
        "白莉爱吃巧克力" -> "Baili loves chocolate"
        "屁股" -> "butt"
        "北条麻妃" -> "Hojo Maki"
        "爆乳" -> "Big breasts"
        "人体艺术" -> "Body Art"
        "死库水" -> "Dead reservoir water"
        "处女膜" -> "hymen"
        "欧美" -> "Europe and America"
        "新娘" -> "bride"
        "波多野结衣无码" -> "Hatano Yui Uncensored"
        "言沫" -> "Yan Mo"
        "乐乐" -> "Lele"
        "内衣走光" -> "Underwear exposed"
        "和服" -> "kimono"
        "反差" -> "Contrast"
        "口爆" -> "blowjob"
        "乱伦" -> "incest"
        "王语瞳" -> "Wang Yutong"
        "美足" -> "beautiful feet"
        "真空" -> "vacuum"
        "张柏芝性爱影片" -> "Cecilia Cheung sex video"
        "修女" -> "nun"
        "梦心月" -> "Meng Xinyue"
        "裙底" -> "skirt"
        "一米八的大梨子" -> "A big pear measuring 1.8 meters"
        "安然" -> "safely"
        "屁眼" -> "asshole"
        "林莎" -> "Lin Sha"
        "露逼" -> "exposed pussy"
        "怀孕" -> "Pregnant"
        "裸体棚拍" -> "Nude studio shoot"
        "屄毛" -> "pussy hair"
        "母子" -> "mother and son"
        "萌琪琪" -> "Meng Qiqi"
        "高跟鞋" -> "High heel"
        "美熟女" -> "beautiful mature woman"
        "肚兜" -> "bellyband"
        "可爱" -> "cute"
        "合集" -> "Collection"
        "潮吹" -> "squirt"
        "秋和柯基" -> "Autumn and Corgi"
        "艾妃" -> "Aifei"
        "啾啾" -> "tweet"
        "六味帝皇酱" -> "Six flavor emperor sauce"
        "台模系列" -> "Table mold series"
        "裸足" -> "bare feet"
        "台模流出" -> "Table mold flows out"
        "马来西亚" -> "Malaysia"
        "日本" -> "Japan"
        "多人" -> "multiple people"
        "东京热" -> "Tokyo Hot"
        "迷之呆梨" -> "Mysterious Pear"
        "怀旧" -> "nostalgia"
        "熟女裸照" -> "MILF Nude Photos"
        "国模超大尺度" -> "National model super large scale"
        "不知火舞" -> "Mai Shiranui"
        "私处照片" -> "Private parts photos"
        "麻酥酥" -> "Ma Susu"
        "娜露" -> "Nalu"
        "大尺" -> "Dachi"
        "魅魔" -> "Succubus"
        "韩模大尺度" -> "Korean model large scale"
        "抖娘" -> "Dou Niang"
        "工口" -> "Erotic"
        "尤果网" -> "yugo.com"
        "女神" -> "goddess"
        "双人" -> "Double"
        "特写" -> "close up"
        "桃乃木" -> "Momonogi"
        "谢忻全裸私密照" -> "Xie Xin's nude private photos"
        "女明星露点" -> "Female celebrity exposure"
        "裸照" -> "nude photos"
        "三上悠亚无码" -> "Mikami Yua Uncensored"
        "吉泽明步" -> "Akiho"
        "裸体模特" -> "nude model"
        "中国" -> "China"
        "紧身" -> "tight"
        "射精" -> "ejaculation"
        "足控" -> "Foot control"
        "多人无码" -> "Multiplayer uncensored"
        "熟女全裸" -> "MILF Nude"
        "推女郎无圣光" -> "Pushing girls without holy light"
        "高跟" -> "high heels"
        "洗澡" -> "bath"
        "泳装" -> "swimsuit"
        "星野秀奈" -> "Hoshino Hidena"
        "方子萱" -> "Fang Zixuan"
        "明日花" -> "Asuka"
        "郭鬼鬼露点" -> "Guo Guigui's exposure point"
        "无码旧图" -> "Uncoded old pictures"
        "宁宁" -> "Ning Ning"
        "诱惑" -> "lure"
        "张静文" -> "Zhang Jingwen"
        "桥本有菜" -> "Hashimoto Arina"
        "小尤奈" -> "Little Yuna"
        "田丽裸体写真集" -> "Tian Li nude photo album"
        "小玲" -> "Xiaoling"
        "热裤" -> "hot pants"
        "美脚" -> "beautiful feet"
        "白茹雪" -> "Bai Ruxue"
        "二穴齐插无码" -> "Two holes penetrated simultaneously without coding"
        "按摩" -> "massage"
        "少女系列" -> "Girls series"
        "林希威" -> "Lin Xiwei"
        "木瓜奶" -> "papaya milk"
        "篠崎爱" -> "Ai Shinozaki"
        "旅拍" -> "Travel photography"
        "蕾菈" -> "Layla"
        "掰穴全集" -> "Complete collection of pussy breaking"
        "熊熊" -> "raging"
        "车模" -> "car model"
        "高潮脸" -> "orgasm face"
        "山岸逢花" -> "Flowers everywhere on the mountain shore"
        "女学生裸照" -> "Female students nude photos"
        "娜娜" -> "Nana"
        "姐妹" -> "sisters"
        "港女" -> "Hong Kong girl"
        "葵司" -> "Aoiji"
        "尿尿" -> "Pee"
        "冲田凛花" -> "Rinka Okita"
        "希威社" -> "Xiweishe"
        "乳首" -> "nipple"
        "吞精" -> "swallow cum"
        "跳蛋" -> "Vibrator"
        // "欧美写真" -> "European and American photos"
        "水手服" -> "Sailor suit"
        "三上" -> "Mikami"
        "花花公子" -> "playboy"
        "天海翼" -> "sky Sea Wing"
        "黄乐然" -> "Huang Leran"
        "丽图" -> "Ritu"
        "乳环" -> "nipple rings"
        "骆驼趾" -> "camel toe"
        "比基尼" -> "bikini"
        "杉原杏璃" -> "Anri Sugihara"
        "素人熟女" -> "Amateur MILF"
        "肉肉" -> "Rourou"
        "峰不二子" -> "Fujiko Mine"
        "摄影" -> "photography"
        "蜜桃社" -> "peach club"
        "无码流出系列" -> "Uncensored leak series"
        "巨乳女优无码" -> "Big breasted actress uncensored"
        "露脸" -> "Show your face"
        "私拍写真做爱" -> "Private photo shoot and sex"
        "刚毛" -> "bristle"
        "米线" -> "rice noodles"
        "上原亚衣" -> "Ai Uehara"
        "刘飞儿露点" -> "Liu Feier's exposure point"
        "棚拍" -> "Studio shot"
        "紧缚写真系列" -> "Tight bondage photo series"
        "学生裸照" -> "Nude photos of students"
        "丽柜" -> "Beautiful cabinet"
        "米砂" -> "rice sand"
        "乳交" -> "Titjob"
        "瑜珈" -> "Yoga"
        "全裸无毛" -> "Nude and hairless"
        "舒淇露点写真" -> "Shu Qi's revealing photos"
        "女优" -> "Actress"
        "王婉悠" -> "Wang Wanyou"
        "小礼好困" -> "Xiaoli is so sleepy"
        "透明内衣" -> "Transparent underwear"
        "模特" -> "model"
        "景甜" -> "Jing Tian"
        "朝桐光" -> "Chao Tongguang"
        "头条女神" -> "headline goddess"
        "米砂露点" -> "rice sand dew point"
        "韩模美女私拍" -> "Korean model beauty private shooting"
        "刘钰儿" -> "Liu Yuer"
        "蕾丝兔宝宝" -> "lace bunny"
        "碧蓝航线" -> "azur lane"
        "小熊乱躺" -> "Little bear lying around"
        "王馨瑶露点" -> "Wang Xinyao exposed spots"
        "无名" -> "nameless"
        "明星全裸" -> "Celebrities naked"
        "女友" -> "girlfriend"
        "雪碧" -> "Sprite"
        "无码套图流出" -> "Uncoded set of pictures leaked"
        "无毛宣言" -> "hairless manifesto"
        "极品韩模" -> "Best Korean model"
        "翁虹" -> "Weng Hong"
        "长腿" -> "long legs"
        "田丽" -> "Tian Li"
        "芝芝" -> "Zhizhi"
        "裸女图" -> "Naked girl pictures"
        "猫九酱" -> "Cat Jiujiang"
        "阿寨寨" -> "azhaizhai"
        "张思允" -> "Zhang Siyun"
        "美腿" -> "beautiful legs"
        "熟女无码" -> "MILF Uncensored"
        "舞蹈" -> "dance"
        "裸乳" -> "Naked breasts"
        "第五人格" -> "fifth personality"
        "大尺度福利图" -> "Large scale welfare map"
        "主播" -> "Anchor"
        "人体" -> "human body"
        "妹妹" -> "younger sister"
        "性感" -> "sexy"
        "杨思敏" -> "Yang Simin"
        "药师小清欣" -> "Pharmacist Xiao Qingxin"
        "裸模" -> "nude model"
        "无水印超大尺度" -> "No watermark super large size"
        "裸体自拍" -> "nude selfie"
        "筱慧" -> "Xiao Hui"
        "神楽板真冬" -> "Kamiruita Mafuyu"
        "人体摄影" -> "body photography"
        "张嘻嘻露点" -> "Zhang Xixi shows off some points"
        "教室" -> "classroom"
        "婕哥" -> "Brother Jie"
        "赵小米" -> "Zhao Xiaomi"
        "栗子外流" -> "chestnuts outflow"
        "白浆" -> "Albic"
        "强暴" -> "rape"
        "无毛妹系列" -> "Hairless Girl Series"
        "一小央泽" -> "A little Yang Ze"
        "唐琪儿露点" -> "Tang Qier's dew point"
        "美少女" -> "Beautiful girl"
        "真冬" -> "true winter"
        "皮衣" -> "Leather jacket"
        "允尔" -> "Yoonji"
        "仙仙桃" -> "fairy peach"
        "露奶头" -> "Showing nipples"
        "大屁股" -> "big ass"
        "张嘻嘻" -> "Zhang Hehe"
        "小妹妹" -> "little sister"
        "汤唯" -> "Tang Wei"
        "套图" -> "Set of pictures"
        "闫盼盼全裸" -> "Yan Panpan naked"
        "辰辰" -> "Chenchen"
        "香菱" -> "Xiangling"
        "邓紫棋" -> "G.E.M"
        "裸图" -> "Nude pictures"
        "温泉" -> "spa"
        "喷水" -> "squirt"
        "芭蕾" -> "ballet"
        "布丁" -> "pudding"
        "玩具" -> "Toy"
        "刺青" -> "tattoo"
        "巨乳全裸" -> "Big breasts naked"
        "白莉" -> "Baili"
        "唐琪儿" -> "Tang Qier"
        "失禁" -> "incontinence"
        "丰满" -> "full"
        "女星" -> "actress"
        "拘束" -> "restrained"
        "陆模插穴" -> "Lu model penetration"
        "吉泽明歩无码" -> "Akiho Yoshizawa Uncensored"
        "无圣光无码" -> "No holy light and no code"
        "盼盼" -> "Panpan"
        "东南亚美女" -> "Southeast Asian beauties"
        "明日方舟" -> "Arknights"
        "无码裸照" -> "Uncensored nude photos"
        "偷拍美女撒尿" -> "Secretly filmed beautiful woman peeing"
        "豪乳" -> "Big breasts"
        "短裙" -> "short skirt"
        "程程程" -> "Cheng Chengcheng"
        "纹身" -> "tattoo"
        "晴儿无码" -> "Qing'er uncensored"
        "微博" -> "Weibo"
        "过期米线露点" -> "Expired rice noodles dew point"
        "没穿" -> "Not wearing anything"
        "眼酱大魔王" -> "Eye sauce devil"
        "杪夏" -> "Jie Xia"
        "年年" -> "every year"
        "鬼灭之刃" -> "Demon Slayer: Kimetsu no Yaiba"
        "北京天使" -> "beijing angel"
        "美模" -> "beautiful model"
        "裤袜" -> "pantyhose"
        "淫妻乱伦无码" -> "Wife incest uncensored"
        "索菲" -> "Sophie"
        "蠢沫沫露点" -> "Stupid Momo dew point"
        "李梓熙" -> "Li Zixi"
        "奈汐酱" -> "Nai Xi-chan"
        "艾妃露点" -> "Aifei dew point"
        "牛仔" -> "cowboy"
        "小雪" -> "Xiaoxue"
        "迪丽热巴" -> "Dilireba"
        "韩模私拍大尺度套图" -> "Korean model's large-scale private photo shoot"
        "韩秋雪" -> "Han Qiuxue"
        "古典" -> "classical"
        "动感" -> "Dynamic"
        "无名外流" -> "Unknown exodus"
        "台湾露三点写真" -> "Taiwan exposed three-point photo"
        "妖精社" -> "Goblin Club"
        "妹妹全裸" -> "Sister naked"
        "瑞莎" -> "Raisa"
        "美臀" -> "beautiful butt"
        "玉足" -> "Yuzu"
        "麻豆" -> "Madou"
        "全裸露出" -> "fully exposed"
        "无码黎菲儿" -> "Uncoded Li Feier"
        "微乳" -> "Microemulsion"
        "上原亜衣" -> "Uehara Ayi"
        "运动内衣" -> "sports bra"
        "自拍裸照" -> "Selfie nude photos"
        "玥儿玥" -> "Yueer Yue"
        "四级" -> "Level 4"
        "郭鬼鬼" -> "Guo Guigui"
        "黑兽" -> "black beast"
        "艾小青" -> "Ai Xiaoqing"
        "女热大陆" -> "Female Hot Continent"
        "韩模非公开" -> "Korean model private"
        "神木丽" -> "Shenmuli"
        "胸部走光" -> "Breast exposed"
        "女大生" -> "female college student"
        "月音瞳" -> "Tsukune Hitomi"
        "菊花" -> "chrysanthemum"
        "张语昕" -> "Zhang Yuxin"
        "小女巫露娜" -> "little witch luna"
        "铃木美咲" -> "Suzuki Misaki"
        "萌白" -> "Mengbai"
        "口交福利姬" -> "Oral sex welfare girl"
        "闪亮亮" -> "Shiny bright"
        "李可可" -> "Li Keke"
        "全露" -> "Fully exposed"
        "素人娘" -> "Amateur girl"
        "蒂法" -> "Tifa"
        "台湾写真女星" -> "Taiwanese photo actress"
        "无码日本" -> "Uncensored Japan"
        "李妍曦" -> "Li Yanxi"
        "恶犬" -> "vicious dog"
        "越南美女" -> "Vietnamese beauties"
        "女王" -> "Queen"
        "香港女星" -> "Hong Kong actress"
        "网红裸照" -> "Internet celebrity nude photos"
        "援交" -> "compensated dating"
        "小胖丁" -> "Little chubby"
        "撸管推荐" -> "Recommended masturbation"
        "高叉" -> "High fork"
        "天心" -> "Tianxin"
        "村上西瓜" -> "Murakami Watermelon"
        "深田" -> "Fukada"
        "微密圈" -> "microcircle"
        "麻生希" -> "Nozomi Aso"
        "私拍套图" -> "Private photoshoot set"
        "有喵酱" -> "There is meow sauce"
        "裸睡" -> "sleep naked"
        "小只马" -> "little horse"
        "国模私拍套图" -> "Chinese model private photoshoot set"
        "果哥" -> "Brother Guo"
        "吴梦梦" -> "Wu Mengmeng"
        "桌布" -> "tablecloth"
        "性感模拍" -> "Sexy model shoot"
        "瑶瑶" -> "Yaoyao"
        "仓井优香" -> "Kurai Yuka"
        "柚子先生" -> "Mr. Yuzu"
        "风吟鸟唱" -> "The wind sings and the birds sing"
        "松下纱栄子" -> "Panasonic Saeko"
        "方子萱露点" -> "Fang Zixuan dew point"
        "真理裤" -> "truth pants"
        "小仓由菜" -> "Ogura Yuna"
        "蓉儿" -> "Ronger"
        "吉沢明歩" -> "Akiho Yoshizawa"
        "土肥圆矮挫穷" -> "The soil is fat, round, short and poor."
        "华模" -> "HuaMo"
        "无圣光福利" -> "No Holy Light benefits"
        "就是阿朱" -> "It's A'Zhu"
        "黄楽然" -> "Huang Jianran"
        "圣光" -> "holy light"
        "心妍小公主" -> "little princess xinyan"
        "蕾拉" -> "Layla"
        "角色扮演" -> "role play"
        "啦啦队" -> "Cheerleading"
        "冯木木" -> "Feng Mumu"
        "章子怡" -> "Zhang Ziyi"
        "陈香菱" -> "Chen Xiangling"
        "安希" -> "Anxi"
        "沐雨柔" -> "Mu Yurou"
        "丝足" -> "Silky feet"
        "妹子裸照" -> "Girl nude photos"
        "浴室" -> "bathroom"
        "顾欣怡" -> "Gu Xinyi"
        "尹菲" -> "Yin Fei"
        "何欣纯" -> "He Xinchun"
        "私房" -> "private house"
        "小云宝宝" -> "Little cloud baby"
        "依依" -> "Yiyi"
        "桜井甯甯" -> "Sakurai Nene"
        "精灵" -> "Elf"
        "夏小秋" -> "Xia Xiaoqiu"
        "松岛枫" -> "Matsushima maple"
        "美尻" -> "Mijiri"
        "桃乃木香奈" -> "Momonogi Kana"
        "小清欣" -> "Xiao Qingxin"
        "浓密阴毛" -> "Thick pubic hair"
        "本土" -> "local"
        "森咲智美" -> "Morisaki Tomomi"
        "清水由乃" -> "Shimizu Yuno"
        "巫女" -> "miko"
        "豆瓣酱" -> "Doubanjiang"
        "呆呆" -> "Dumb"
        "金鱼" -> "goldfish"
        "千夜未来" -> "Qianye future"
        "辜莞允口交" -> "Gu Wanyun blowjob"
        "早安图片" -> "good morning images"
        "若兮" -> "Ruoxi"
        "男女做爱图" -> "Sex pictures of men and women"
        "美鲍图集" -> "Beautiful abalone atlas"
        "林文文" -> "Lin Wenwen"
        "绅士龙虾" -> "Gentleman Lobster"
        "梓梓外流" -> "Zi Zi's exodus"
        "凉森" -> "Liangsen"
        "辜莞允" -> "Gu Guanyun"
        "双飞" -> "Flying together"
        "小薇" -> "Xiaowei"
        "紧急企划" -> "emergency planning"
        "艺术" -> "Art"
        "花嫁" -> "flower wedding"
        "六味" -> "Six flavors"
        "吴倩" -> "Wu Qian"
        "佐山爱" -> "Sayama Ai"
        "林美惠子" -> "Hayashi Mieko"
        "北岛玲" -> "Kitajima Rei"
        "沈佳熹" -> "Shen Jiaxi"
        "明日花绮罗" -> "Asuka Kirara"
        "落落" -> "Luoluo"
        "神乐坂真冬" -> "Kagurazaka Mafuyu"
        "睡衣" -> "pajamas"
        "办公室" -> "office"
        // "丝袜美腿" -> "beautiful legs in stockings"
        "奶瓶" -> "baby bottle"
        "石川澪" -> "Ishikawa Mio"
        "网搜大尺度系列" -> "Online search large scale series"
        "美心" -> "Maxim's"
        "无码口交" -> "Uncensored blowjob"
        "王李丹妮" -> "Wang Lidanni"
        "女警" -> "policewoman"
        "换妻" -> "Wife swapping"
        "漫展" -> "comic con"
        "桥本" -> "Hashimoto"
        "小玲私拍" -> "Xiaoling's private photos"
        "潘娇娇" -> "Pan Jiaojiao"
        "狗头" -> "dog head"
        "全裸无遮" -> "Nude without cover"
        "阿包也是兔娘" -> "Abao is also a bunny girl"
        "王俪丁" -> "Wang Liding"
        "小仓千代" -> "Ogura Chiyo"
        "泳衣" -> "swimsuit"
        "佐歌奈" -> "Sakana"
        "冲田" -> "Okita"
        "相约中国" -> "Meet in China"
        "男人装" -> "Men's clothing"
        "土肥圆" -> "Tufeiyuan"
        // "极品美女" -> "Top beauty"
        "青山知可子" -> "Chikako Aoyama"
        "自拍照片" -> "Selfie photo"
        "老婆" -> "Wife"
        "椎名" -> "Shiina"
        "刻晴" -> "Qingqing"
        "林襄写真外流" -> "Lin Xiang’s photos leaked"
        "加勒比" -> "caribbean"
        "时间停止" -> "time stops"
        "日本美熟女" -> "Japanese beautiful mature woman"
        "雷电将军" -> "Thunder General"
        "阿姨" -> "Aunt"
        "下着" -> "It's raining"
        "漏点" -> "Missing point"
        "熊小诺" -> "Xiong Xiaonuo"
        "微胖" -> "Slightly fat"
        "辻本杏" -> "Tsujimoto Anzu"
        "学校" -> "School"
        "尾巴" -> "Tail"
        "大乱交" -> "Big orgy"
        "日本女优无码" -> "Japanese actress uncensored"
        "璃奈酱" -> "Rina-chan"
        "白灵" -> "Bai Ling"
        "潘春春" -> "Pan Chunchun"
        "卿卿" -> "Qingqing"
        "东热" -> "Dongre"
        "美女" -> "Beauty"
        "肥臀" -> "Fat butt"
        "森萝" -> "Senluo"
        "明星露点走光" -> "Celebrity exposure"
        "相泽南" -> "Minami Aizawa"
        "山手梨爱" -> "Yamate Ria"
        "飘飘" -> "Fluttering"
        "狂三" -> "Kurumi"
        "紧身衣" -> "tights"
        "圣诞" -> "Christmas"
        "杨颖" -> "Yang Ying"
        "小黎" -> "Xiao Li"
        "完具少女" -> "perfect girl"
        "萌萌" -> "Mengmeng"
        "超短裙" -> "miniskirt"
        "网络" -> "network"
        "蜜桃" -> "peach"
        "妞妞" -> "Niuniu"
        "啪啪" -> "bang bang"
        "徐微微" -> "Xu Weiwei"
        "皮裤" -> "leather pants"
        "早期" -> "Early days"
        "玛鲁娜" -> "Maruna"
        "小恩" -> "Xiao En"
        "片山萌美" -> "Katayama Moemi"
        "小奈奈" -> "Xiao Nana"
        "色情明星色图" -> "Porn star porn pictures"
        "网红外流照片" -> "Internet celebrity streaming photos"
        "小早川怜子" -> "Reiko Kobayakawa"
        "奶牛" -> "dairy cow"
        "大学" -> "University"
        "小野夕子" -> "Ono Yuko"
        "筱崎爱" -> "Ai Shinozaki"
        "椎名空" -> "Sora Shiina"
        "模特养成" -> "Model development"
        "台湾艺人走光照" -> "Taiwanese artists take the spotlight"
        "开腿" -> "open legs"
        "喵糖映画" -> "Meow Sugar Movie"
        "尤蜜荟" -> "Youmihui"
        "洛丽塔大哥" -> "Brother Lolita"
        "欣杨" -> "Xin Yang"
        "紧缚桟敷紧缚" -> "bind tightly, bind tightly"
        "元元" -> "Yuan Yuan"
        "海贼王" -> "One Piece"
        "邵雨薇露点" -> "Shao Yuwei dew point"
        "陆模私拍系列" -> "Chinese model private shooting series"
        "母亲" -> "Mother"
        "八重神子" -> "Yae Shenzi"
        "嫩模唐安琪私拍" -> "Private photoshoot of young model Tang Anqi"
        "桃桃酱" -> "peach jam"
        "沫沫" -> "Momo"
        "云溪溪" -> "Yunxixi"
        "樱桃喵" -> "Cherry Meow"
        "鲔鱼露点照" -> "Tuna exposed photos"
        "染谷有香" -> "Some valleys are fragrant"
        "舞蹈生" -> "Dancer"
        "无忌" -> "Wuji"
        "孟狐狸" -> "Meng Fox"
        "明星外流照片" -> "Leaked photos of celebrities"
        "二穴" -> "Two points"
        "上原瑞穂" -> "Mizuho Uehara"
        "风间由美" -> "Yumi Kazama"
        "舒淇露第四点" -> "Shu Qilu's fourth point"
        "小子怡" -> "Xiao Ziyi"
        "杨紫嫣" -> "Yang Ziyan"
        "张筱雨" -> "Zhang Xiaoyu"
        "西瓜少女" -> "watermelon girl"
        "浅仓唯" -> "Asakura Yui"
        "希威" -> "Seaway"
        "大乳晕" -> "big areola"
        "梦心" -> "dream heart"
        "河北" -> "Hebei"
        "连裤袜" -> "pantyhose"
        "戸田真琴" -> "Toda Makoto"
        "香草喵露露" -> "Vanilla Meow Lulu"
        "北原多香子无码" -> "Kitahara Takako Uncensored"
        "下药" -> "drugged"
        "骨感" -> "Skinny"
        "婷婷" -> "Tingting"
        "熟妇" -> "MILF"
        "芊芊" -> "flourishing"
        "性感东南亚" -> "Sexy Southeast Asia"
        "樱空桃" -> "cherry empty peach"
        "精品" -> "Boutique"
        "热巴" -> "Reba"
        "天然" -> "natural"
        "秋瓷炫" -> "Choo Ja Hyun"
        "郭鬼鬼外流" -> "Guo Guigui's exodus"
        "草莓味的软糖" -> "Strawberry flavored gummies"
        "摇摇乐" -> "shake music"
        "娜美" -> "Nami"
        "王者" -> "King"
        "蕾姆" -> "Rem"
        "裸体无码" -> "Nude uncensored"
        "校园露出" -> "campus exposed"
        "过膝袜" -> "Knee socks"
        "古川" -> "Furukawa"
        "橙子喵" -> "orange meow"
        "菌烨" -> "bacteria ye"
        "解婕翎" -> "Xie Jieling"
        "全裸巨乳自慰" -> "Naked big breasts masturbation"
        "波多野" -> "Hatano"
        "抱走莫子" -> "Take Mozi away"
        "大胸" -> "Big breasts"
        "木木森" -> "Mumusen"
        "裸贷" -> "naked loan"
        "大尺度私拍台模" -> "Large scale private photography table model"
        "李雅" -> "Li Ya"
        "女女" -> "female female"
        "福利姬露出" -> "Welfare Ji exposed"
        "孕妇裸照" -> "Pregnant women nude photos"
        "合成" -> "synthesis"
        "工口小妖精" -> "Erotic goblin"
        "张馨予" -> "Viann Zhang"
        "脱衣" -> "strip"
        "台模小君" -> "Table model Xiaojun"
        "尹甜甜" -> "Yin Tiantian"
        "蠢沫沫裸" -> "Stupid Momo Naked"
        "港台女星露点" -> "Hong Kong and Taiwan actress exposure points"
        "雷姆" -> "Rem"
        "李丽莎大尺度" -> "Li Lisa large scale"
        "全裸女神" -> "Nude goddess"
        "筱田优" -> "Shinoda Yu"
        "小蔡头喵喵喵" -> "Little Cai Tou Meow Meow Meow"
        "古装裸体" -> "costume nude"
        "礼服" -> "dress"
        "鲔鱼外流" -> "Tuna outflow"
        "台湾女艺人私拍" -> "Private photography of Taiwanese female artists"
        "星宫一花" -> "Ichika Hoshinomiya"
        "若隐若现" -> "looming"
        "肉棒" -> "cock"
        "酒店" -> "hotel"
        "利世露点" -> "Lee World Dew Point"
        "米砂外流" -> "Outflow of rice and sand"
        "秀人网大尺度" -> "Xiuren.com large scale"
        "梓梓" -> "Zi Zi"
        "桜井" -> "Sakurai"
        "白皙" -> "Fair-skinned"
        "全脱全裸" -> "Take off all naked"
        "日本巨乳写真" -> "Japanese big breasts photos"
        "毛衣" -> "sweater"
        "掰穴图" -> "Acupuncture point diagram"
        "东南亚" -> "Southeast Asia"
        "香草" -> "vanilla"
        "婕咪" -> "Jamie"
        "熟女女优" -> "MILF Actress"
        "动感小站私拍" -> "Dynamic small station private shooting"
        "四月桐" -> "April Tung"
        "本土全裸写真" -> "Local nude photos"
        "知一妹妹" -> "Know my sister"
        "小宵虎南" -> "Xiaoxiao Hunan"
        "李元玲" -> "Li Yuanling"
        "君岛美绪" -> "Kimijima Mio"
        "旬果" -> "Xun Guo"
        "凯竹" -> "kaizhu"
        "口罩" -> "Face mask"
        "桃园娜美" -> "Taoyuan Nami"
        "白金" -> "platinum"
        "陈香菱漏点流出" -> "Chen Xiangling leaked out"
        "克拉女神" -> "Goddess Carat"
        "台模" -> "Table mold"
        "二次元" -> "Two dimensions"
        "韩国模特养成" -> "Korean model training"
        "森咲智美露点" -> "Morisaki Tomomi dew points"
        "国模方子萱" -> "Chinese model Fang Zixuan"
        "小穴照" -> "Pussy photos"
        "明星合成裸照" -> "Composite nude photos of celebrities"
        "田冰冰" -> "Tian Bingbing"
        "催眠" -> "Hypnosis"
        "太平洋娘熟女" -> "Pacific MILF"
        "闺蜜" -> "best friend"
        "西西" -> "Xixi"
        "会有妻" -> "Will have a wife"
        "漏尿" -> "leakage of urine"
        "张柏芝无码" -> "Cecilia Cheung Uncensored"
        "韩模系列" -> "Korean model series"
        "天然素人" -> "natural amateur"
        "软软" -> "Soft"
        "奥田咲" -> "Okuda Saki"
        "裸模持" -> "Naked model"
        "仙仙辰" -> "Xianxianchen"
        "韩模试镜" -> "Korean model audition"
        "厕所小便" -> "Peeing in the toilet"
        "外拍" -> "Outdoor shooting"
        "柳侑绮" -> "Liu Youqi"
        "卓娅祺" -> "Zhuo Yaqi"
        "本庄玲" -> "Rei Honjo"
        "早期露点" -> "early dew point"
        "脸红" -> "blush"
        "日暮" -> "sunset"
        "粉穴性感" -> "Sexy pink pussy"
        "软萌" -> "Soft and cute"
        "李沁" -> "Li Qin"
        "谢薇安" -> "Xie Wei'an"
        "重口" -> "heavy mouth"
        "腋毛" -> "armpit hair"
        "三点" -> "three o'clock"
        "绯月樱" -> "Scarlet Moon Sakura"
        "尤妮丝露点" -> "Eunice Dew Spot"
        "凑莉久" -> "Riku Minato"
        "石原希望" -> "Nozomi Ishihara"
        "小仙" -> "Xiaoxian"
        "艺人全裸写真" -> "Artist nude photos"
        "図鉴" -> "図jian"
        "推特女神外流" -> "Twitter goddess leaked"
        "无码无修正" -> "Uncoded and uncorrected"
        "藤浦惠" -> "Megumi Fujiura"
        "小逗逗" -> "Xiao Doudou"
        "日本女优群交" -> "Japanese actress group sex"
        "粉穴" -> "pink hole"
        "舞小喵" -> "Wu Xiaomiao"
        "抄底" -> "bargain hunting"
        "绿帽" -> "green hat"
        "拷问" -> "torture"
        "安心亚" -> "Amber"
        "露点套图" -> "Dew point set"
        "温心怡" -> "Wen Xinyi"
        "果咩酱" -> "Fruit sauce"
        "猫九" -> "cat nine"
        "尺度" -> "scale"
        "校花" -> "school beauty"
        "王瑞儿" -> "Wang Ruier"
        "郭静纯" -> "Guo Jingchun"
        "周淑怡" -> "Zhou Shuyi"
        "崩坏" -> "Collapse"
        "前女友" -> "Ex-girlfriend"
        "熊小诺无圣光" -> "Xiong Xiaonuo has no holy light"
        "日本女优写真" -> "Japanese actress photos"
        "韩模智宇" -> "Han Mo Ji Woo"
        "擘穴" -> "Break acupoints"
        "肉感" -> "sensual"
        "毛鲍" -> "hairy abalone"
        "美国" -> "USA"
        "女生裸照" -> "Girls nude photos"
        "篠田优" -> "Shinoda Yu"
        "南桃" -> "Nantao"
        "胡桃" -> "walnut"
        "贫奶" -> "Poor milk"
        "混血" -> "mixed race"
        "网袜" -> "fishnet stockings"
        "气质" -> "temperament"
        "蔡依林" -> "Jolin Tsai"
        // "亚洲美女" -> "asian beauty"
        "麻仓忧" -> "Asakura worry"
        "双胞胎" -> "twin"
        "云烧" -> "cloud burning"
        "爆机少女" -> "Explosive girl"
        "横山美雪" -> "Miyuki Yokoyama"
        "夏暮光" -> "summer twilight"
        "眼酱" -> "Eye sauce"
        "西野翔" -> "Nishino Sho"
        "五十路熟女写真" -> "Fifty-year-old mature woman photos"
        "樱井" -> "Sakurai"
        "模范学院" -> "model college"
        "米妮" -> "Minnie"
        "皮皮奶" -> "Pipi Nai"
        "羽庭" -> "Yuting"
        "巨根" -> "huge root"
        "无码国模" -> "Uncoded Chinese model"
        "夏美酱露点" -> "Natsumi sauce dew point"
        "蜜桃臀" -> "peach butt"
        "小模" -> "small model"
        "彩美旬果" -> "Aimei Shunguo"
        "张贺玉" -> "Zhang Heyu"
        "漫展走光" -> "Exposed at Comic Exhibition"
        "外拍流出" -> "Outside shooting leaked"
        "林襄写真" -> "Lin Xiang's photo"
        "二次元福利" -> "Second dimension welfare"
        "野外裸体" -> "Nude in the wild"
        "港模大尺度" -> "Hong Kong model large scale"
        "深田咏美无码" -> "Fukada Eimi Uncensored"
        "奶咪" -> "Boobs"
        "疯猫" -> "crazy cat"
        "奈汐" -> "Nai Xi"
        "健身房" -> "Gym"
        "陈冠希事件" -> "Edison Chen incident"
        "老熟女" -> "old woman"
        "是小逗逗" -> "It's Xiao Doudou"
        "完具酱" -> "Wan Gujiang"
        "陈雅漫" -> "Chen Yaman"
        "雪碧外流" -> "Sprite leaks"
        "国模娜娜" -> "Chinese model Nana"
        "平胸" -> "flat chest"
        "不穿内裤" -> "no underwear"
        "屌照" -> "Dick photos"
        "罗莉" -> "Luo Li"
        "瓜希酱" -> "Guahi Sauce"
        "峮峮" -> "峳宮"
        "旅馆裸拍" -> "Hotel nude shoot"
        "枫可怜" -> "Poor maple"
        "李雅柔" -> "Li Yarou"
        "石原莉奈" -> "Rina Ishihara"
        "全裸套图" -> "Full nude set"
        "无码破解版" -> "Uncoded cracked version"
        "裸体露毛" -> "Nude and hairy"
        "夜雨" -> "night rain"
        "于子涵" -> "Yu Zihan"
        "饭岛爱" -> "Ai Iijima"
        "做爱无修正" -> "Make love without modification"
        "馒头" -> "Steamed bun"
        "夏晴子" -> "Xia Qingzi"
        "妖精" -> "goblin"
        "小舞" -> "Xiao Wu"
        "水著" -> "water works"
        "于大小姐" -> "Miss Yu"
        "夜火" -> "night fire"
        "雪平莉左" -> "Yukihira Rizuo"
        "羞耻" -> "shame"
        "日奈娇" -> "Hinajiao"
        "杨幂裸照" -> "Yang Mi nude photos"
        "痴女" -> "Slut"
        "张宇婷" -> "Zhang Yuting"
        "骨感全裸" -> "skinny naked"
        "熟女人妻" -> "mature wife"
        "内射图" -> "injectogram"
        "黑胡同" -> "dark alley"
        "连体" -> "Siamese"
        "火影" -> "Naruto"
        "高桥" -> "Takahashi"
        "阴环" -> "Yin ring"
        "子涵" -> "Sub-Han"
        "三浦惠理子" -> "Eriko Miura"
        "李宗瑞" -> "Li Zongrui"
        "汤加丽" -> "Tang Jiali"
        "谢忻外流照片" -> "Xie Xin leaked photos"
        "无内丝袜" -> "No inner stockings"
        "西瓜" -> "watermelon"
        "王雨纯裸" -> "Wang Yuchun nude"
        "侑芯" -> "You Xin"
        "贵妇掰穴" -> "Lady's vaginal penetration"
        "安斋拉拉" -> "anjailala"
        "赤鬼伯伯" -> "Uncle Red Ghost"
        "相册破解" -> "Album crack"
        "泷泽劳拉" -> "Takizawa Laura"
        "蜜汁" -> "honey juice"
        "无名破解流出" -> "Unnamed crack leaked"
        "绝对领域" -> "absolute realm"
        "漫画" -> "comics"
        "街拍走光" -> "Exposed in street photography"
        "布布" -> "Bubu"
        "软软酱" -> "Soft sauce"
        "小蔡头" -> "Xiao Caitou"
        "迷奸" -> "rape"
        "浜崎真绪" -> "Hamasaki Mao"
        "麻酥酥哟" -> "Numb and crispy"
        "天海" -> "Tianhai"
        "捷克" -> "Czech Republic"
        else -> chinese
    }
}
