package eu.kanade.tachiyomi.extension.en.manhwamanganet

import eu.kanade.tachiyomi.multisrc.bakamanga.BakaManga

class ManhwaMangaNet : BakaManga(
    "ManhwaManga.net",
    "https://manhwamanga.net",
    "en",
) {
    override fun getGenreList() = arrayOf(
        Pair("All", ""),
        Pair("Action", "action"),
        Pair("Adult", "adult"),
        Pair("Adventure", "adventure"),
        Pair("BL", "bl"),
        Pair("Comedy", "comedy"),
        Pair("Comics", "comics"),
        Pair("Doujinshi", "doujinshi"),
        Pair("Drama", "drama"),
        Pair("Ecchi", "ecchi"),
        Pair("Fantasy", "fantasy"),
        Pair("Gender Bender", "gender-bender"),
        Pair("GL", "gl"),
        Pair("Harem", "harem"),
        Pair("Hentai", "hentai"),
        Pair("Historical", "historical"),
        Pair("Horror", "horror"),
        Pair("Isekai", "isekai"),
        Pair("Josei", "josei"),
        Pair("Manhwa", "manhwa"),
        Pair("Martial Arts", "martial-arts"),
        Pair("Mature", "mature"),
        Pair("Mecha", "mecha"),
        Pair("Mystery", "mystery"),
        Pair("NTR", "ntr"),
        Pair("Psychological", "psychological"),
        Pair("Raw", "raw"),
        Pair("Romance", "romance"),
        Pair("School Life", "school-life"),
        Pair("Sci-fi", "sci-fi"),
        Pair("Seinen", "seinen"),
        Pair("Shoujo", "shoujo"),
        Pair("Shounen", "shounen"),
        Pair("Slice of Life", "slice-of-life"),
        Pair("Smut", "smut"),
        Pair("Sports", "sports"),
        Pair("Supernatural", "supernatural"),
        Pair("Thriller", "thriller"),
        Pair("Tragedy", "tragedy"),
        Pair("Webtoon", "webtoon"),
        Pair("Webtoons", "webtoons"),
        Pair("Yaoi", "yaoi"),
        Pair("Yuri", "yuri"),
    )
}
